### ISSUE TITLE
Not an issue actually

### ISSUE THREAD

**Issue by denishonig** [seleznev/redmine-helper#1]
Привет!

Извини, не нашел другого способа как с тобой связаться. Ищу к себе в команду инфраструктурных инженеров. Хотел бы с тобой пообщаться по этому поводу. Какой предпочтительный способ связи с тобой?

**Comment by seleznev** [comment]
Добрый день!

Вернул в профиль email (seleznev.ru@gmail.com). Альтернативы: телефон, Telegram (могу в почте отправить номер).
